apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberize-operator
  namespace: kuberize-system
  labels:
    {{- include "kuberize.labels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kuberize-api
  namespace: kuberize-system
  labels:
    {{- include "kuberize.labels" . | nindent 4 }}
